#!/bin/bash

# Install flake8 (if it's not already there)
if [ ! -f `which flake8` ]
then
  echo "Installing flake8... couldn't find it."
  sudo pip3 install flake8
fi

flake8 --show-pep8 --show-source --exclude=settings.py,wsgi.py \
  browse/*.py peerreviewed/*.py new/*.py
