# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 05:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 4, 5, 4, 11, 114476, tzinfo=utc)),
        ),
    ]
