# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160404_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(),
        ),
    ]
