# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160405_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_scheme',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_demo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default=datetime.datetime(2016, 4, 28, 0, 31, 11, 642354, tzinfo=utc), max_length=100),
        ),
    ]
