# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160504_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default=datetime.datetime(2016, 5, 4, 16, 46, 17, 302659, tzinfo=utc), max_length=100),
        ),
    ]
