# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20160511_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default=datetime.datetime(2016, 5, 11, 3, 29, 56, 213548, tzinfo=utc), max_length=100),
        ),
    ]
