# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20160511_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default=datetime.datetime(2016, 5, 11, 19, 25, 46, 745872, tzinfo=utc), max_length=100),
        ),
    ]
