# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20160511_1624'),
        ('accounts', '0018_auto_20160511_1925'),
    ]

    operations = [
    ]
