# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20160511_2051'),
        ('accounts', '0018_auto_20160511_1624'),
    ]

    operations = [
    ]
