# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160511_2155'),
        ('accounts', '0019_merge'),
        ('accounts', '0023_auto_20160511_2054'),
        ('accounts', '0020_auto_20160511_2123'),
    ]

    operations = [
    ]
