# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 20:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0002_auto_20160203_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Review_Votes',
            new_name='ReviewVotes',
        ),
        migrations.AddField(
            model_name='professor',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 3, 20, 7, 40, 331217, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 3, 20, 7, 45, 507127, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 3, 20, 7, 50, 875173, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 3, 20, 7, 54, 771962, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='email_pattern',
            field=models.CharField(max_length=100, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AddField(
            model_name='field',
            name='categories',
            field=models.ManyToManyField(to='browse.FieldCategories'),
        ),
        migrations.AddField(
            model_name='field',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='fields',
            field=models.ManyToManyField(to='browse.Field'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.School'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Department'),
        ),
    ]
