# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_review_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldCategories',
            new_name='FieldCategory',
        ),
        migrations.RenameModel(
            old_name='ReviewVotes',
            new_name='ReviewVote',
        ),
        migrations.AlterModelOptions(
            name='fieldcategory',
            options={'verbose_name_plural': 'Field Categories'},
        ),
        migrations.AlterModelOptions(
            name='reviewvote',
            options={'verbose_name_plural': 'Review Votes'},
        ),
    ]
