# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 15:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0010_auto_20160217_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100000, validators=[django.core.validators.MinLengthValidator(25)])),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=100000, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Review'),
        ),
    ]
