# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0010_auto_20160217_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_difficulty',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating_overall',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
