# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0011_auto_20160316_0257'),
        ('browse', '0011_auto_20160316_1529'),
    ]

    operations = [
    ]
