# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0012_review_title'),
        ('browse', '0012_merge'),
    ]

    operations = [
    ]
