# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0013_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100000)),
                ('rating', models.FloatField()),
                ('flag', models.CharField(choices=[('LD', 'Lewd.'), ('UH', 'Unhelpful.'), ('OT', 'Off Topic.'), ('OK', 'Okay.')], default='OK', max_length=2)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Review')),
            ],
            options={
                'verbose_name_plural': 'Peer Reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'verbose_name_plural': 'Review Comments'},
        ),
    ]
