# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0014_auto_20160413_2125'),
        ('browse', '0014_auto_20160406_1526'),
    ]

    operations = [
    ]
