# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0015_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=100)),
                ('color_scheme', models.IntegerField()),
                ('is_demo', models.BooleanField()),
            ],
        ),
    ]
