# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0016_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='timezone',
            field=models.CharField(default=datetime.datetime(2016, 4, 28, 0, 24, 54, 704425, tzinfo=utc), max_length=100),
        ),
    ]
