# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0017_peerreview_is_finished'),
        ('browse', '0018_delete_settings'),
    ]

    operations = [
    ]
