# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0019_merge'),
        ('browse', '0018_auto_20160502_2025'),
    ]

    operations = [
    ]
