# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0020_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='target',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Professor'),
        ),
    ]
