# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0021_auto_20160510_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.Course'),
        ),
    ]
