# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0022_auto_20160510_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Professor'),
        ),
    ]
