# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0023_auto_20160510_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='avatar',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
